language: c
sudo: required
dist: trusty

services:
  - docker

env:
  - OS=debian
  - OS=fedora

before_script:
  - docker build -t libxmlb-${OS} -f contrib/ci/Dockerfile-${OS} .

script:
  - docker run -t -v `pwd`:/build libxmlb-${OS} ./contrib/ci/build_and_test.sh

jobs:
  include:
    - stage: abi
      name: "Check for ABI breaks"
      env:
        - OS=fedora
      before_script:
        - docker build -t libxmlb-${OS} -f contrib/ci/Dockerfile-${OS} .
      script:
        - docker run -t -v `pwd`:/build libxmlb-${OS} ./contrib/ci/check-abi $(git describe --abbrev=0 --tags) $(git rev-parse HEAD)
